name: Add PRs and issues to Octokit org project

on:
  issues:
    types: [reopened, opened]
  pull_request_target:
    types: [reopened, opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: ${{ secrets.OCTOKITBOT_PROJECT_ACTION_TOKEN && 'https://github.com/orgs/octokit/projects/10' || '' }}
          github-token: ${{ secrets.OCTOKITBOT_PROJECT_ACTION_TOKEN || github.token }}
          labeled: "Status: Stale"
          label-operator: NOT
